#!/usr/bin/env bash
# Install Cheats Manager and its Fish integration on macOS or Linux.
set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
dry_run=false

if [[ "${1:-}" == "--dry-run" ]]; then
    dry_run=true
elif [[ $# -gt 0 ]]; then
    printf 'Uso: %s [--dry-run]\n' "$0" >&2
    exit 2
fi

run() {
    if "$dry_run"; then
        printf '+ '
        printf '%q ' "$@"
        printf '\n'
    else
        "$@"
    fi
}

as_root() {
    if [[ "$(id -u)" -eq 0 ]]; then
        run "$@"
    elif command -v sudo >/dev/null 2>&1; then
        run sudo "$@"
    else
        printf 'Se requiere sudo para instalar dependencias del sistema.\n' >&2
        exit 1
    fi
}

missing=()
for command in fish fzf python3 less; do
    command -v "$command" >/dev/null 2>&1 || missing+=("$command")
done
if command -v python3 >/dev/null 2>&1 && ! python3 -m venv --help >/dev/null 2>&1; then
    missing+=("python3-venv")
fi

if [[ ${#missing[@]} -gt 0 ]]; then
    case "$(uname -s)" in
        Darwin)
            if ! command -v brew >/dev/null 2>&1; then
                printf 'Falta Homebrew. Instalalo desde https://brew.sh y ejecutá este script otra vez.\n' >&2
                exit 1
            fi
            run brew install fish fzf python
            ;;
        Linux)
            if command -v apt-get >/dev/null 2>&1; then
                as_root apt-get update
                as_root apt-get install -y fish fzf python3 python3-venv less
            elif command -v zypper >/dev/null 2>&1; then
                as_root zypper --non-interactive install --no-recommends fish fzf python3 python3-venv less
            elif command -v dnf >/dev/null 2>&1; then
                as_root dnf install -y fish fzf python3 less
            elif command -v pacman >/dev/null 2>&1; then
                as_root pacman -Sy --noconfirm fish fzf python less
            elif command -v apk >/dev/null 2>&1; then
                as_root apk add fish fzf python3 py3-pip less
            else
                printf 'No encontré un gestor soportado. Instalá: fish, fzf, python3, python3-venv y less.\n' >&2
                exit 1
            fi
            ;;
        *)
            printf 'Sistema no soportado: %s\n' "$(uname -s)" >&2
            exit 1
            ;;
    esac
fi

venv_python="$repo_dir/.venv/bin/python"
if [[ ! -x "$venv_python" ]]; then
    run python3 -m venv "$repo_dir/.venv"
fi
run "$venv_python" -m pip install --upgrade pip
run "$venv_python" -m pip install -r "$repo_dir/requirements.txt"

fish_state_home="${XDG_STATE_HOME:-$HOME/.local/state}/chats-manager/fish"
bootstrap_file="$fish_state_home/cheats_manager.fish"
custom_aliases_file="$fish_state_home/cheats_manager_aliases.fish"

run mkdir -p "$fish_state_home"
if [[ ! -f "$custom_aliases_file" ]]; then
    if "$dry_run"; then
        printf '+ create %q\n' "$custom_aliases_file"
    else
        printf '# Custom aliases managed by Cheats Manager\n' > "$custom_aliases_file"
    fi
fi

if "$dry_run"; then
    printf '+ create %q\n' "$bootstrap_file"
else
    repo_escaped="$(fish -c 'string escape -- $argv[1]' "$repo_dir")"
    aliases_escaped="$(fish -c 'string escape -- $argv[1]' "$custom_aliases_file")"
    cat > "$bootstrap_file" <<EOF
# Generated by Cheats Manager install.sh
set -gx CS_CHEATS_DIR $repo_escaped
set -gx CS_FISH_ALIASES_FILE $aliases_escaped
source "\$CS_CHEATS_DIR/fish_aliases_example.fish"
EOF
fi

if ! "$dry_run"; then
    fish -c 'source "$argv[1]"; functions -q cs; functions -q csfind' "$bootstrap_file"
fi

printf '\nCheats Manager quedó instalado. Abrí una nueva terminal Fish o ejecutá:\n'
printf '  source %q\n' "$bootstrap_file"
printf '  cs\n'
